name: mle-dev
channels:
  - defaults
dependencies:
  - pip:
    - contourpy
    - cycler
    - fonttools
    - joblib
    - kiwisolver
    - matplotlib
    - numpy
    - packaging
    - pandas
    - pillow
    - pyparsing
    - python-dateutil
    - pytz
    - scikit-learn
    - scipy
    - six
    - sixer
    - threadpoolctl
    - tzdata