name: Build Package Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install tree CLI tool
      run: sudo apt-get update && sudo apt-get install tree

    - name: Display directory tree before building
      run: tree

    - name: Build Package
      run: |
        echo "Building package..."

    - name: Display directory tree after building
      run: tree

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-package
        path: .
