name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display directory tree before building
      run: tree

    - name: Build Package
      run: |
        echo "Building package..."
        # Add your package building commands here

    - name: Display directory tree after building
      run: tree

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-package
        path: .

  setup_environment_and_run_tests:
    runs-on: ubuntu-latest
    needs: build_package
    steps:
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: built-package
        path: .

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Initialize Conda and activate the environment
      run: |
        conda init bash
        source ~/.bashrc
        conda activate mle-dev

    - name: Execute python script on flake8
      run: |
        conda run -n mle-dev flake8 nonstandardcode.py

    - name: Execute python script within Conda environment
      run: |
        conda run -n mle-dev python nonstandardcode.py
