name: Create Conda Environment

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv  # Name of the conda environment
        environment-file: environment.yml  # Path to your environment.yml file relative to repository root

    - name: Install dependencies
      run: |
        conda install --file environment.yml
