name: Create Conda Environment
on:
  push:
    branches:
      - main

runs-on: ubuntu-latest
defaults:
  run:
    shell: bash -el {0}
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Miniconda and Create Environment
    uses: conda-incubator/setup-miniconda@v3
    with:
      activate-environment: anaconda-client-env
      environment-file: environment.yml

  - name: Display Conda Information
    run: |
      conda info
      conda list