name: Create Conda Environment

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Initialize Conda
      run: conda init bash

    - name: Activate Conda environment
      run: conda activate myenv