name: Create Conda Environment

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3

    - name: Create Conda environment
      run: conda env create -f environment.yml

    - name: Initialize Conda and activate the environment
      run: |
        conda init bash
        source ~/.bashrc
        conda activate mle-dev

    - name: Execute python script on flake8
      run: |
        conda run -n mle-dev flake8 nonstandardcode.py

    - name: Execute python script within Conda environment
      run: |
        conda run -n mle-dev python nonstandardcode.py
